const exDirectory = `
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/ACB_CTs/ACB_CTs.php
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Rogowski_Coils/Clamp-on_Rogowski_Coils.php                                                         
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Rogowski_Coils/Clamp-on_Rogowski_Coils_002.php                                                     
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Rogowski_Coils/Flexible_Rogowski_Coils.php                                                         
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Rogowski_Coils/MV_Flexible_Rogowski_Coils.php                                                      
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Rogowski_Coils/Rigid_Rogowski_Coils.php                                                            
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Rogowski_Coils/Rogowski_Coils.php                                                                  
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Smart_Meters/Smart_Meters.php                                                                      
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Solid_CT/DC_Immune_CT.php                                                                          
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Solid_CT/High_Frequency_Monitoring_CT.php                                                          
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Solid_CT/Multi-Harmonics_Monitoring_CT.php                                                         
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Solid_CT/Protection&Monitoring_CT.php                                                              
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Solid_CT/Revenue_Grade_Metering_CT.php                                                             
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Solid_CT/Solid_CT.php                                                                              
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Solid_CT/Voltage_Measurement_CT.php                                                                
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Split-core_CT/Busbar-Split-core_CT.php                                                             
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Split-core_CT/Miniature-Split-core_CT.php                                                          
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Split-core_CT/Outdoor-Split-Core-transformer.php                                                   
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Split-core_CT/Outdoor-Split-Core-transformer_201117.php                                            
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Split-core_CT/Split-core_CT.php                                                                    
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Zero-Phase_CT/Zero-Phase_CT.php                                                                    
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/Zero-Phase_CT/Zero-Phase_CT_Dep01.php                                                              
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/aboutus/index.php
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/contacts/index.php
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/download.php
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/en_v1/index.php
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/inc/btn-up.php
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/inc/footer.php
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/inc/head.php
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/inc/header.php
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/index.php
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/index_backup_220720.php                                                                            
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/inquiry/index.php
/Users/minseocha/Desktop/projects/태화트랜스/Taehwa_demo/www/inquiry/mail.php
`
