/**
 * Generate API wrapper for handling basePath in client-side fetch calls
 *
 * Creates src/lib/api.ts that automatically prepends NEXT_PUBLIC_EGDESK_BASE_PATH
 * to relative URLs, solving the Next.js basePath limitation with client-side fetch.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

/**
 * Detect if project uses src/ directory structure
 */
function usesSrcDirectory(projectPath: string): boolean {
  const srcPath = path.join(projectPath, 'src');
  const srcAppPath = path.join(projectPath, 'src', 'app');
  return fs.existsSync(srcPath) && fs.existsSync(srcAppPath);
}

/**
 * Ensure lib directory exists
 */
function ensureLibDirectory(projectPath: string): string {
  const hasSrc = usesSrcDirectory(projectPath);
  const libDir = hasSrc
    ? path.join(projectPath, 'src', 'lib')
    : path.join(projectPath, 'lib');

  if (!fs.existsSync(libDir)) {
    fs.mkdirSync(libDir, { recursive: true });
    console.log(`📁 Created directory: ${libDir}`);
  }

  return libDir;
}

/**
 * Generate src/lib/api.ts file for basePath-aware fetch wrapper
 */
export function generateApiWrapper(projectPath: string): void {
  const libDir = ensureLibDirectory(projectPath);
  const apiPath = path.join(libDir, 'api.ts');

  console.log(`📝 Generating API wrapper at: ${apiPath}`);

  // Check if api.ts already exists
  if (fs.existsSync(apiPath)) {
    console.log('⚠️  api.ts already exists - backing up to api.backup.ts');
    const backupPath = path.join(libDir, 'api.backup.ts');
    fs.copyFileSync(apiPath, backupPath);
  }

  const apiContent = `/**
 * API Fetch Wrapper for EGDesk Tunneling
 *
 * This wrapper automatically prepends NEXT_PUBLIC_EGDESK_BASE_PATH to relative URLs.
 * This is necessary because Next.js basePath does NOT automatically apply to
 * client-side fetch() calls - it's a known limitation.
 *
 * Generated by @egdesk/next-api-plugin
 */

const basePath = process.env.NEXT_PUBLIC_EGDESK_BASE_PATH || '';

/**
 * Fetch wrapper that handles basePath for tunneled environments
 *
 * @example
 * // ❌ Wrong - will return 404 in tunneled environment
 * fetch('/api/transactions')
 *
 * @example
 * // ✅ Correct - automatically prepends basePath
 * apiFetch('/api/transactions')
 *
 * @param path - The API path (e.g., '/api/transactions')
 * @param options - Standard fetch options
 */
export async function apiFetch(path: string, options?: RequestInit): Promise<Response> {
  // Automatically prepend basePath to relative URLs
  const url = path.startsWith('/') && !path.startsWith('//')
    ? \`\${basePath}\${path}\`
    : path;

  return fetch(url, options);
}
`;

  fs.writeFileSync(apiPath, apiContent.replace(/\r?\n/g, os.EOL), 'utf-8');
  console.log(`✅ Generated ${apiPath}`);
}
