/**
 * Generate Next.js 16+ proxy for EGDesk database proxy
 *
 * Creates proxy.ts that intercepts __user_data_proxy requests
 * and forwards them to the EGDesk MCP server.
 *
 * This is the Next.js 16+ recommended approach (replaces middleware.ts)
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

/**
 * Detect if project uses src/ directory structure
 */
function usesSrcDirectory(projectPath: string): boolean {
  const srcPath = path.join(projectPath, 'src');
  const srcAppPath = path.join(projectPath, 'src', 'app');
  return fs.existsSync(srcPath) && fs.existsSync(srcAppPath);
}

/**
 * Generate proxy.ts file in the correct location (root or src/)
 */
export function generateProxy(projectPath: string): void {
  // Detect if project uses src/ directory
  const hasSrc = usesSrcDirectory(projectPath);
  const targetDir = hasSrc ? path.join(projectPath, 'src') : projectPath;
  const proxyPath = path.join(targetDir, 'proxy.ts');

  console.log(`📁 Detected ${hasSrc ? 'src/' : 'root'} directory structure`);
  console.log(`📝 Generating proxy at: ${proxyPath}`);

  // Check if proxy.ts already exists
  if (fs.existsSync(proxyPath)) {
    console.log('⚠️  proxy.ts already exists - backing up to proxy.backup.ts');
    const backupPath = path.join(targetDir, 'proxy.backup.ts');
    fs.copyFileSync(proxyPath, backupPath);
  }

  const proxyContent = `import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

/**
 * EGDesk Database Proxy (Next.js 16+)
 *
 * Intercepts __user_data_proxy, __browser_recording_proxy, and __internal_knowledge_proxy requests
 * and forwards them to the EGDesk MCP HTTP server. This avoids CORS in local and tunneled environments.
 *
 * Generated by @egdesk/next-api-plugin
 */
export async function proxy(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Intercept __user_data_proxy requests
  if (pathname.includes('__user_data_proxy')) {
    try {
      const body = await request.text();

      // Read API key and URL from environment
      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const headers: HeadersInit = {
        'Content-Type': 'application/json',
      };

      if (apiKey) {
        headers['X-Api-Key'] = apiKey;
      }

      // Forward to EGDesk MCP server
      const response = await fetch(\`\${apiUrl}/user-data/tools/call\`, {
        method: 'POST',
        headers,
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__browser_recording_proxy')) {
    try {
      const body = await request.text();

      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const headers: HeadersInit = {
        'Content-Type': 'application/json',
      };

      if (apiKey) {
        headers['X-Api-Key'] = apiKey;
      }

      const response = await fetch(\`\${apiUrl}/browser-recording/tools/call\`, {
        method: 'POST',
        headers,
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__internal_knowledge_proxy')) {
    try {
      const body = await request.text();

      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const headers: HeadersInit = {
        'Content-Type': 'application/json',
      };

      if (apiKey) {
        headers['X-Api-Key'] = apiKey;
      }

      const response = await fetch(\`\${apiUrl}/internal-knowledge/tools/call\`, {
        method: 'POST',
        headers,
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  // Continue to next proxy or route
  return NextResponse.next();
}

export const config = {
  matcher: [
    /*
     * Match all paths except static assets
     * The proxy function filters for __user_data_proxy / __browser_recording_proxy / __internal_knowledge_proxy
     */
    '/:path*',
  ],
};
`;

  fs.writeFileSync(proxyPath, proxyContent.replace(/\r?\n/g, os.EOL), 'utf-8');
  console.log(`✅ Generated ${proxyPath}`);
}
