/**
 * Generate Next.js middleware for EGDesk database proxy
 *
 * Creates middleware.ts that intercepts __user_data_proxy requests
 * and forwards them to the EGDesk MCP server.
 */

import * as fs from 'fs';
import * as path from 'path';

/**
 * Generate middleware.ts file in the project root
 */
export function generateMiddleware(projectPath: string): void {
  const middlewarePath = path.join(projectPath, 'middleware.ts');

  // Check if middleware.ts already exists
  if (fs.existsSync(middlewarePath)) {
    console.log('⚠️  middleware.ts already exists - backing up to middleware.backup.ts');
    const backupPath = path.join(projectPath, 'middleware.backup.ts');
    fs.copyFileSync(middlewarePath, backupPath);
  }

  const middlewareContent = `import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

/**
 * EGDesk Database Proxy Middleware
 *
 * Intercepts __user_data_proxy requests and forwards them to the EGDesk MCP server.
 * This allows CORS-free database access in both local and tunneled environments.
 *
 * Generated by @egdesk/next-api-plugin
 */
export async function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Intercept __user_data_proxy requests
  if (pathname.includes('__user_data_proxy')) {
    try {
      const body = await request.text();

      // Read API key and URL from environment
      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const headers: HeadersInit = {
        'Content-Type': 'application/json',
      };

      if (apiKey) {
        headers['X-Api-Key'] = apiKey;
      }

      // Forward to EGDesk MCP server
      const response = await fetch(\`\${apiUrl}/user-data/tools/call\`, {
        method: 'POST',
        headers,
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  // Continue to next middleware or route
  return NextResponse.next();
}

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    '/((?!api|_next/static|_next/image|favicon.ico).*)',
  ],
};
`;

  fs.writeFileSync(middlewarePath, middlewareContent, 'utf-8');
  console.log(`✅ Generated ${middlewarePath}`);
}
