import fs from "node:fs";
import path from "node:path";
import { app } from "electron";
import os from "node:os";

export interface YouTubeVideoGenerationOptions {
  /** Script/text content for the video */
  script?: string;
  /** Title to display in the video */
  title?: string;
  /** Background color (hex) */
  backgroundColor?: string;
  /** Text color (hex) */
  textColor?: string;
  /** Duration in seconds (default: 7) */
  duration?: number;
  /** Output file path (optional - will generate if not provided) */
  outputPath?: string;
}

/**
 * Generate a 7-second short-style video for YouTube Shorts using Gemini Veo API
 * Creates a vertical video (9:16 aspect ratio) using AI video generation
 */
export async function generateYouTubeShortVideo(
  options: YouTubeVideoGenerationOptions
): Promise<string> {
  const {
    script = "YouTube Short",
    title = "New Video",
    duration = 7,
    outputPath,
  } = options;

  console.log('[generateYouTubeShortVideo] Starting video generation using Gemini Veo API...');
  console.log('[generateYouTubeShortVideo] Duration:', duration, 'seconds');
  console.log('[generateYouTubeShortVideo] Title:', title);
  console.log('[generateYouTubeShortVideo] Script:', script);

  // Check for GEMINI_API_KEY
  if (!process.env.GEMINI_API_KEY) {
    throw new Error(
      "GEMINI_API_KEY environment variable is required to generate videos using Gemini Veo API."
    );
  }

  // Determine output path
  const tempDir = app?.getPath?.("temp") || os.tmpdir();
  const outputDir = path.join(tempDir, "egdesk-youtube-videos");
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const finalOutputPath =
    outputPath ||
    path.join(outputDir, `youtube-short-${Date.now()}.mp4`);

  try {
    // Import GoogleGenAI
    const { GoogleGenAI } = await import("@google/genai");
    
    // Initialize AI client
    const ai = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY,
    });

    // Build video generation prompt from script and title
    // Combine title and script into a descriptive video prompt
    let videoPrompt = script;
    if (title && title !== "New Video") {
      videoPrompt = `${title}. ${script}`;
    }

    // For YouTube Shorts (vertical video), add aspect ratio instruction
    // Note: Gemini Veo generates videos based on prompt, aspect ratio may vary
    console.log('[generateYouTubeShortVideo] Generating video with Gemini Veo...');
    console.log('[generateYouTubeShortVideo] Prompt:', videoPrompt);

    // Start video generation
    let operation = await ai.models.generateVideos({
      model: "veo-3.1-generate-preview",
      prompt: videoPrompt,
    });

    console.log('[generateYouTubeShortVideo] Video generation operation started, waiting for completion...');

    // Poll the operation status until the video is ready
    const maxWaitTime = 600000; // 10 minutes max
    const startTime = Date.now();
    let pollCount = 0;

    while (!operation.done) {
      // Check timeout
      if (Date.now() - startTime > maxWaitTime) {
        throw new Error('Video generation timeout - exceeded 10 minutes');
      }

      pollCount++;
      if (pollCount % 6 === 0) { // Log every minute
        console.log(`[generateYouTubeShortVideo] Still waiting for video generation... (${Math.floor((Date.now() - startTime) / 1000)}s elapsed)`);
      }

      // Wait 10 seconds before checking again
      await new Promise((resolve) => setTimeout(resolve, 10000));

      // Get updated operation status
      operation = await ai.operations.getVideosOperation({
        operation: operation,
      });
    }

    console.log('[generateYouTubeShortVideo] Video generation completed!');

    // Check if video was generated
    if (!operation.response?.generatedVideos || operation.response.generatedVideos.length === 0) {
      throw new Error('No video was generated by Gemini Veo API');
    }

    // Download the generated video
    console.log('[generateYouTubeShortVideo] Downloading generated video...');
    const videoFile = operation.response.generatedVideos[0].video;
    
    if (!videoFile) {
      throw new Error('Generated video file reference is missing');
    }

    // Download the video file
    await ai.files.download({
      file: videoFile,
      downloadPath: finalOutputPath,
    });

    // Verify file was created
    if (!fs.existsSync(finalOutputPath)) {
      throw new Error("Video file was not downloaded successfully");
    }

    const fileStats = fs.statSync(finalOutputPath);
    console.log(
      `[generateYouTubeShortVideo] Video generated and saved successfully: ${finalOutputPath} (${(fileStats.size / 1024 / 1024).toFixed(2)} MB)`
    );

    return finalOutputPath;
  } catch (error) {
    console.error("[generateYouTubeShortVideo] Error generating video:", error);
    throw new Error(
      `Failed to generate video: ${error instanceof Error ? error.message : "Unknown error"}`
    );
  }
}


